#!/usr/bin/env python3
"""Generate crates/lumen/src/cldr_units.rs from CLDR JSON (unicode-org/cldr-json).

Fetches per-locale unit display patterns (long/short/narrow, count=one/other) for the ECMA-402
sanctioned units plus a few common compound units, and emits a Rust lookup table:

    pub fn unit_pattern(loc, unit, style, plural) -> Option<&'static str>

`loc` is a CLDR locale key ("de", "ja", "zh-Hant", ...); the pattern contains a "{0}" placeholder.
Run: python3 scripts/gen-cldr-units.py > crates/lumen/src/cldr_units.rs
"""
import json
import sys
import urllib.request

BASE = "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-units-full/main"

# CLDR locale keys we ship unit data for (zh split by script).
LOCALES = [
    "en", "en-IN", "de", "fr", "es", "it", "pt", "nl", "ja", "ko",
    "zh-Hant", "zh-Hans", "ru", "ar", "pl",
]

# The ECMA-402 sanctioned single units, plus common compound units used by tests.
UNITS = [
    "acre", "bit", "byte", "celsius", "centimeter", "day", "degree", "fahrenheit",
    "fluid-ounce", "foot", "gallon", "gigabit", "gigabyte", "gram", "hectare", "hour",
    "inch", "kilobit", "kilobyte", "kilogram", "kilometer", "liter", "megabit", "megabyte",
    "meter", "microsecond", "mile", "mile-scandinavian", "milliliter", "millimeter",
    "millisecond", "minute", "month", "nanosecond", "ounce", "percent", "petabyte", "pound",
    "second", "stone", "terabit", "terabyte", "week", "yard", "year",
    "kilometer-per-hour", "meter-per-second",
]

STYLES = ["long", "short", "narrow"]
PLURALS = ["one", "other"]


def fetch(loc):
    url = f"{BASE}/{loc}/units.json"
    with urllib.request.urlopen(url) as r:
        return json.load(r)["main"][loc]["units"]


def find_key(style_map, unit):
    # CLDR keys are "<category>-<unit>"; match the one whose suffix is our unit.
    for key in style_map:
        if key == unit or key.endswith("-" + unit):
            return key
    return None


def main():
    # entries: (loc, unit, style, plural) -> pattern
    rows = []
    for loc in LOCALES:
        try:
            units = fetch(loc)
        except Exception as e:  # noqa: BLE001
            print(f"// WARN {loc}: {e}", file=sys.stderr)
            continue
        for style in STYLES:
            sm = units.get(style, {})
            for unit in UNITS:
                key = find_key(sm, unit)
                if not key:
                    continue
                entry = sm[key]
                for pl in PLURALS:
                    pat = entry.get(f"unitPattern-count-{pl}")
                    if pat:
                        rows.append((loc, unit, style, pl, pat))

    out = []
    out.append("//! CLDR unit display patterns, generated by scripts/gen-cldr-units.py. DO NOT EDIT.")
    out.append("//! `{0}` is the number placeholder.")
    out.append("")
    out.append("#[rustfmt::skip]")
    out.append(f"const UNIT_PATTERNS: [(&str, &str, &str, &str, &str); {len(rows)}] = [")
    for loc, unit, style, pl, pat in rows:
        pat = pat.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'    ("{loc}", "{unit}", "{style}", "{pl}", "{pat}"),')
    out.append("];")
    out.append("")
    out.append("/// The unit display pattern for a CLDR locale key, unit, style and plural category.")
    out.append("pub fn unit_pattern(loc: &str, unit: &str, style: &str, plural: &str) -> Option<&'static str> {")
    out.append("    UNIT_PATTERNS")
    out.append("        .iter()")
    out.append("        .find(|(l, u, s, p, _)| *l == loc && *u == unit && *s == style && *p == plural)")
    out.append("        .map(|(_, _, _, _, pat)| *pat)")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
