#!/usr/bin/env python3
"""Generate crates/lumen/src/cldr_dates.rs from CLDR JSON (unicode-org/cldr-json).

Fetches per-locale, per-calendar month names (wide/abbreviated/narrow, "format" context) and era
names, emitting Rust lookup tables:

    pub fn month_name(loc, cal, width, month) -> Option<&'static str>   // month is 1-based
    pub fn era_name(loc, cal, width, era) -> Option<&'static str>       // era is the CLDR index

Run: python3 scripts/gen-cldr-dates.py > crates/lumen/src/cldr_dates.rs
"""
import json
import sys
import urllib.request

ROOT = "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json"


def pkg_for(cal):
    """The cldr-json package holding a calendar's data (gregorian is in cldr-dates-full)."""
    if cal == "gregory":
        return "cldr-dates-full"
    fam = {
        "ethioaa": "ethiopic",
        "islamic-civil": "islamic",
        "islamic-tbla": "islamic",
        "islamic-umalqura": "islamic",
    }.get(cal, cal)
    return f"cldr-cal-{fam}-full"

LOCALES = ["en", "de", "fr", "es", "it", "pt", "nl", "ja", "ko", "zh-Hant", "zh-Hans", "ru", "ar"]

# Our calendar id -> CLDR ca-file basename.
CALENDARS = {
    "gregory": "gregorian",
    "buddhist": "buddhist",
    "japanese": "japanese",
    "roc": "roc",
    "coptic": "coptic",
    "ethiopic": "ethiopic",
    "ethioaa": "ethiopic-amete-alem",
    "hebrew": "hebrew",
    "islamic": "islamic",
    "islamic-civil": "islamic-civil",
    "islamic-tbla": "islamic-tbla",
    "islamic-umalqura": "islamic-umalqura",
    "persian": "persian",
    "indian": "indian",
    "chinese": "chinese",
    "dangi": "dangi",
}

WIDTHS = {"long": "wide", "short": "abbreviated", "narrow": "narrow"}


def fetch(loc, ca_file):
    url = f"{BASE}/{loc}/ca-{ca_file}.json"
    with urllib.request.urlopen(url) as r:
        return json.load(r)["main"][loc]["dates"]["calendars"][ca_file.replace("-", "-")]


def main():
    months = []  # (loc, cal, width, month_num, name)
    eras = []  # (loc, cal, width, era_key, name)
    for loc in LOCALES:
        for cal, ca_file in CALENDARS.items():
            key = ca_file
            try:
                url = f"{ROOT}/{pkg_for(cal)}/main/{loc}/ca-{ca_file}.json"
                with urllib.request.urlopen(url) as r:
                    data = json.load(r)["main"][loc]["dates"]["calendars"][key]
            except Exception as e:  # noqa: BLE001
                print(f"// WARN {loc}/{ca_file}: {e}", file=sys.stderr)
                continue
            m = data.get("months", {}).get("format", {})
            for width, cw in WIDTHS.items():
                for num, name in m.get(cw, {}).items():
                    # Skip non-numeric keys (e.g. Hebrew "7-yeartype-leap").
                    if not num.isdigit():
                        continue
                    months.append((loc, cal, width, int(num), name))
            e = data.get("eras", {})
            for width, ekey in (("long", "eraNames"), ("short", "eraAbbr"), ("narrow", "eraNarrow")):
                for ec, name in e.get(ekey, {}).items():
                    if "alt" in ec:
                        continue
                    eras.append((loc, cal, width, ec, name))

    def esc(s):
        return s.replace("\\", "\\\\").replace('"', '\\"')

    out = ["//! CLDR month/era names, generated by scripts/gen-cldr-dates.py. DO NOT EDIT.", ""]
    out.append("#[rustfmt::skip]")
    out.append(f"const MONTHS: [(&str, &str, &str, u8, &str); {len(months)}] = [")
    for loc, cal, width, num, name in months:
        out.append(f'    ("{loc}", "{cal}", "{width}", {num}, "{esc(name)}"),')
    out.append("];")
    out.append("")
    out.append("#[rustfmt::skip]")
    out.append(f"const ERAS: [(&str, &str, &str, &str, &str); {len(eras)}] = [")
    for loc, cal, width, ec, name in eras:
        out.append(f'    ("{loc}", "{cal}", "{width}", "{ec}", "{esc(name)}"),')
    out.append("];")
    out.append("")
    out.append("/// The month name (1-based) for a locale/calendar/width, if shipped.")
    out.append("pub fn month_name(loc: &str, cal: &str, width: &str, month: u8) -> Option<&'static str> {")
    out.append("    MONTHS.iter()")
    out.append("        .find(|(l, c, w, m, _)| *l == loc && *c == cal && *w == width && *m == month)")
    out.append("        .map(|(_, _, _, _, n)| *n)")
    out.append("}")
    out.append("")
    out.append("/// The era name for a locale/calendar/width/era-key, if shipped.")
    out.append("pub fn era_name(loc: &str, cal: &str, width: &str, era: &str) -> Option<&'static str> {")
    out.append("    ERAS.iter()")
    out.append("        .find(|(l, c, w, e, _)| *l == loc && *c == cal && *w == width && *e == era)")
    out.append("        .map(|(_, _, _, _, n)| *n)")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
