#!/usr/bin/env python3
"""Generate crates/lumen/src/cldr_likely.rs from CLDR likelySubtags data.

Fetches unicode-org/cldr-json cldr-core/supplemental/likelySubtags.json and emits a sorted
`(key, value)` table plus a binary-search `likely(key) -> Option<&'static str>` for the Add/Remove
Likely Subtags algorithms (Intl.Locale maximize/minimize).

Run: python3 scripts/gen-cldr-likely.py > crates/lumen/src/cldr_likely.rs
"""
import json
import urllib.request

URL = ("https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/"
       "cldr-core/supplemental/likelySubtags.json")


def main():
    data = json.load(urllib.request.urlopen(URL))["supplemental"]["likelySubtags"]
    # Keys/values are language tags using "_" separators; normalize to "-".
    entries = sorted((k.replace("_", "-"), v.replace("_", "-")) for k, v in data.items())

    out = ["//! CLDR likelySubtags table, generated by scripts/gen-cldr-likely.py. DO NOT EDIT.", ""]
    out.append("#[rustfmt::skip]")
    out.append(f"static LIKELY: [(&str, &str); {len(entries)}] = [")
    for k, v in entries:
        out.append(f'    ("{k}", "{v}"),')
    out.append("];")
    out.append("")
    out.append("/// The maximized tag for a likelySubtags search key, if present.")
    out.append("pub fn likely(key: &str) -> Option<&'static str> {")
    out.append("    LIKELY.binary_search_by(|(k, _)| (*k).cmp(key)).ok().map(|i| LIKELY[i].1)")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
