#!/usr/bin/env python3
"""Generate crates/lumen/src/numbering.rs — the digit glyphs of every CLDR "numeric" numbering system,
so Intl.NumberFormat/DateTimeFormat can render digits in adlm/arab/deva/… systems.

Source: unicode-org/cldr common/supplemental/numberingSystems.xml (fetched over the network, like the
tz DB / Unicode property codegen). No external Python deps.
"""
import html
import re
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/numberingSystems.xml"


def unescape(digits):
    # Resolve &#xNNNN; / &#NNN; numeric entities, leaving literal chars intact.
    def repl(m):
        return chr(int(m.group(1), 16) if m.group(1) else int(m.group(2)))
    s = re.sub(r"&#x([0-9A-Fa-f]+);|&#(\d+);", lambda m: chr(int(m.group(1), 16)) if m.group(1) else chr(int(m.group(2))), digits)
    return s


def main():
    src = open(sys.argv[1]).read() if len(sys.argv) > 1 else urllib.request.urlopen(URL, timeout=60).read().decode()
    systems = []
    for m in re.finditer(r'<numberingSystem\s+id="([^"]+)"\s+type="numeric"\s+digits="([^"]+)"', src):
        name, digits = m.group(1), unescape(m.group(2))
        assert len(digits) == 10, f"{name}: {len(digits)} digits"
        systems.append((name, digits))
    systems.sort()

    out = ["//! Digit glyphs of each CLDR numeric numbering system, generated by scripts/gen-numbering.py.",
           "//! DO NOT EDIT.\n"]
    out.append(f"/// (system id, its ten digit glyphs 0-9). "
               f"`latn` is ASCII and handled directly, so it is omitted.")
    out.append(f"pub const NUMBERING: [(&str, [char; 10]); {sum(1 for n,_ in systems if n!='latn')}] = [")
    for name, digits in systems:
        if name == "latn":
            continue
        chars = ", ".join(f"'\\u{{{ord(c):X}}}'" for c in digits)
        out.append(f'    ("{name}", [{chars}]),')
    out.append("];")
    open("crates/lumen/src/numbering.rs", "w").write("\n".join(out) + "\n")
    print(f"wrote crates/lumen/src/numbering.rs ({len(systems)} numeric systems)")


if __name__ == "__main__":
    main()
