#!/usr/bin/env python3
"""Generate crates/lumen/src/units.rs — the sanctioned single-unit identifiers for Intl.NumberFormat
(ECMA-402 IsSanctionedSingleUnitIdentifier). Each CLDR "category-unit" id contributes the unit part
(after the category), e.g. length-kilometer -> kilometer, acceleration-g-force -> g-force.

Source: unicode-org/cldr common/validity/unit.xml (fetched, like the other codegen). No deps.
"""
import re
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/validity/unit.xml"


def main():
    src = open(sys.argv[1]).read() if len(sys.argv) > 1 else urllib.request.urlopen(URL, timeout=60).read().decode()
    m = re.search(r"<id type='unit'[^>]*>(.*?)</id>", src, re.S)
    units = set()
    for tok in m.group(1).split():
        if "-" in tok:
            units.add(tok.split("-", 1)[1])  # strip the category segment
    units = sorted(units)
    out = ["//! Sanctioned single-unit identifiers for Intl.NumberFormat, generated by",
           "//! scripts/gen-units.py from CLDR validity/unit.xml. DO NOT EDIT.\n"]
    out.append(f"pub const SANCTIONED_UNITS: [&str; {len(units)}] = [")
    for i in range(0, len(units), 4):
        out.append("    " + " ".join(f'"{u}",' for u in units[i:i + 4]))
    out.append("];")
    open("crates/lumen/src/units.rs", "w").write("\n".join(out) + "\n")
    print(f"wrote crates/lumen/src/units.rs ({len(units)} units)")


if __name__ == "__main__":
    main()
